Python and SQL Interview Preparation

Objective

To practice important Python programming questions and SQL queries commonly asked in technical interviews, along with their code, prompts, and outputs.

Tools Used

- Google Colab
- Python
- SQLite

Approach

Each question includes a prompt, code or SQL query, and its expected output.

In [ ]:
# Question 1: Check whether a number is even or odd

num = 10

if num % 2 == 0:
    print("Even")
else:
    print("Odd")

Even

Question 2: Reverse a String

Prompt: Write a Python program to reverse a given string.

Concept: String slicing

In [ ]:
text = "Python"
reversed_text = text[::-1]

print("Original string:", text)
print("Reversed string:", reversed_text)

Original string: Python
Reversed string: nohtyP

Question 3: Find the Largest Number in a List

Prompt: Write a Python program to find the largest number in a list of numbers.

Concept: Lists and the "max()" function

In [ ]:
numbers = [10, 25, 8, 40, 15]

largest = max(numbers)

print("Largest number:", largest)

Largest number: 40

Question 4: Check Palindrome

Prompt: Write a Python program to check whether a given string is a palindrome.

Concept: String slicing and if-else statements

In [ ]:
word = "madam"

if word == word[::-1]:
    print("Palindrome")
else:
    print("Not a palindrome")

Palindrome

Question 5: Count Vowels in a String

Prompt: Write a Python program to count the number of vowels in a given string.

Concept: Strings, loops, conditions, and the "sum()" function

In [ ]:
text = "education"
vowels = "aeiou"

count = sum(1 for ch in text.lower() if ch in vowels)

print("Number of vowels:", count)

Number of vowels: 5

SQL Interview Questions

SQL (Structured Query Language) is used to store, retrieve, and manage data in databases.

The following questions demonstrate important SQL queries commonly asked in interviews.

In [ ]:
import sqlite3
import pandas as pd

conn = sqlite3.connect(":memory:")

cursor = conn.cursor()

cursor.execute("""
CREATE TABLE Employee (
    ID INTEGER,
    Name TEXT,
    Department TEXT,
    Salary INTEGER
)
""")

cursor.executemany("""
INSERT INTO Employee VALUES (?, ?, ?, ?)
""", [
    (1, "Ravi", "IT", 25000),
    (2, "Priya", "HR", 40000),
    (3, "Arun", "IT", 35000),
    (4, "Sita", "Sales", 30000),
    (5, "Kiran", "IT", 50000)
])

conn.commit()

print("Employee table created successfully.")

Employee table created successfully.

SQL Question 1: Display All Employees

Prompt: Write an SQL query to display all records from the Employee table.

Concept: SELECT statement

In [ ]:
query = "SELECT * FROM Employee"

pd.read_sql_query(query, conn)

   ID   Name Department  Salary
0   1   Ravi         IT   25000
1   2  Priya         HR   40000
2   3   Arun         IT   35000
3   4   Sita      Sales   30000
4   5  Kiran         IT   50000

SQL Question 2: Filter Employees by Salary

Prompt: Write an SQL query to display the names and salaries of employees whose salary is greater than 30,000.

Concept: SELECT and WHERE statements

In [ ]:
query = """
SELECT Name, Salary
FROM Employee
WHERE Salary > 30000
"""

pd.read_sql_query(query, conn)

    Name  Salary
0  Priya   40000
1   Arun   35000
2  Kiran   50000

SQL Question 3: Find the Highest Salary

Prompt: Write an SQL query to find the employee who earns the highest salary.

Concept: ORDER BY and LIMIT

In [ ]:
query = """
SELECT Name, Salary
FROM Employee
ORDER BY Salary DESC
LIMIT 1
"""

pd.read_sql_query(query, conn)

    Name  Salary
0  Kiran   50000

SQL Question 4: Count Employees in Each Department

Prompt: Write an SQL query to count the number of employees in each department.

Concept: GROUP BY and COUNT()

In [ ]:
query = """
SELECT Department, COUNT(*) AS Employee_Count
FROM Employee
GROUP BY Department
ORDER BY Department
"""

pd.read_sql_query(query, conn)

  Department  Employee_Count
0         HR               1
1         IT               3
2      Sales               1

SQL Question 5: Find the Second-Highest Salary

Prompt: Write an SQL query to find the second-highest distinct salary from the Employee table.

Concept: Subquery and MAX() function

In [ ]:
query = """
SELECT MAX(Salary) AS Second_Highest_Salary
FROM Employee
WHERE Salary < (SELECT MAX(Salary) FROM Employee)
"""

pd.read_sql_query(query, conn)

   Second_Highest_Salary
0                  40000